window.templateCategories = [
  {key:'all', label:'Все'},
  {key:'invite', label:'Пригласительные'},
  {key:'date', label:'На свидание'},
  {key:'landing', label:'Лендинги'},
  {key:'portfolio', label:'Портфолио'},
  {key:'business', label:'Бизнес'},
  {key:'wedding', label:'Свадьба'},
  {key:'birthday', label:'Дни рождения'}
];

window.templatesData = [
  {title:'Наша свадьба', subtitle:'Ирина & Алексей', category:['all','invite','wedding'], theme:'wedding'},
  {title:'День рождения', subtitle:'Праздник, который объединяет', category:['all','invite','birthday'], theme:'birthday'},
  {title:'Путешествия', subtitle:'Новые места. Новые истории.', category:['all','landing'], theme:'travel'},
  {title:'Бизнес', subtitle:'Развивай свои идеи', category:['all','business','landing'], theme:'business'},
  {title:'Портфолио', subtitle:'Покажи себя миру', category:['all','portfolio'], theme:'portrait'},
  {title:'Свидание', subtitle:'История одного вечера', category:['all','date'], theme:'date'},
  {title:'Модный бренд', subtitle:'Коллекция нового сезона', category:['all','business','landing'], theme:'minimal'},
  {title:'Студия', subtitle:'Услуги и команда', category:['all','business','landing'], theme:'studio'},
  {title:'Baby shower', subtitle:'Тёплый семейный день', category:['all','invite'], theme:'wedding'},
  {title:'Открытие салона', subtitle:'Красиво и современно', category:['all','business','landing'], theme:'business'},
  {title:'Детский праздник', subtitle:'Яркое настроение', category:['all','invite','birthday'], theme:'birthday'},
  {title:'Профиль мастера', subtitle:'Личный мини‑сайт', category:['all','landing'], theme:'minimal'},
  {title:'Love story', subtitle:'Наша романтика', category:['all','date'], theme:'date'},
  {title:'Creative folio', subtitle:'Работы и кейсы', category:['all','portfolio'], theme:'portrait'},
  {title:'Luxury event', subtitle:'Премиальное событие', category:['all','invite'], theme:'business'},
  {title:'Travel diary', subtitle:'Путешествие по миру', category:['all','landing'], theme:'travel'},
  {title:'Свадебный вечер', subtitle:'С любовью и светом', category:['all','invite','wedding'], theme:'wedding'},
  {title:'Кондитерская', subtitle:'Сладкий лендинг', category:['all','business','landing'], theme:'birthday'},
  {title:'Фотограф', subtitle:'Ваш визуальный стиль', category:['all','portfolio'], theme:'portrait'},
  {title:'Нежное свидание', subtitle:'План на двоих', category:['all','date'], theme:'date'},
  {title:'Мастер‑класс', subtitle:'Соберите аудиторию', category:['all','business','landing'], theme:'studio'},
  {title:'Birthday neon', subtitle:'Праздник в огнях', category:['all','invite','birthday'], theme:'birthday'},
  {title:'Свадьба floral', subtitle:'Любовь в деталях', category:['all','invite','wedding'], theme:'wedding'},
  {title:'Личный блог', subtitle:'Минимализм и мысли', category:['all','landing'], theme:'minimal'},
  {title:'Дизайнер', subtitle:'Современное портфолио', category:['all','portfolio'], theme:'portrait'},
  {title:'Магазин одежды', subtitle:'Запуск новой коллекции', category:['all','business','landing'], theme:'business'},
  {title:'Weekend date', subtitle:'Тёплая встреча', category:['all','date'], theme:'date'},
  {title:'Семейный праздник', subtitle:'Добрые воспоминания', category:['all','invite'], theme:'wedding'},
  {title:'Travel card', subtitle:'Покажи маршрут', category:['all','landing'], theme:'travel'},
  {title:'Creative studio', subtitle:'Команда и услуги', category:['all','business'], theme:'studio'},
  {title:'Модельное портфолио', subtitle:'Сильный визуал', category:['all','portfolio'], theme:'portrait'},
  {title:'Признание', subtitle:'Страница для особого дня', category:['all','date'], theme:'date'},
  {title:'Юбилей', subtitle:'Торжественный вечер', category:['all','invite','birthday'], theme:'birthday'},
  {title:'Свадебное утро', subtitle:'Лёгкий романтичный стиль', category:['all','invite','wedding'], theme:'wedding'},
  {title:'Food project', subtitle:'Вкусный лендинг', category:['all','business','landing'], theme:'business'},
  {title:'Trip memories', subtitle:'Моменты путешествий', category:['all','landing'], theme:'travel'},
  {title:'Фрилансер', subtitle:'Кейсы и контакты', category:['all','portfolio','landing'], theme:'minimal'},
  {title:'Премьера бренда', subtitle:'Ваша идея растёт', category:['all','business'], theme:'studio'},
  {title:'Moon date', subtitle:'Для особенного вечера', category:['all','date'], theme:'date'},
  {title:'Праздничный вечер', subtitle:'Весело и красиво', category:['all','invite','birthday'], theme:'birthday'}
];
